site/src/ApiBundle/Entity/LexTool.php
<?php

namespace Carmen\ApiBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * LexTool
 *
 * @ORM\Table(name="carmen.lex_tool")
 * @ORM\Entity
 */
class LexTool
{
    /**
     * @var integer
     *
     * @ORM\Column(name="tool_id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(sequenceName="carmen.lex_tool_tool_id_seq", allocationSize=1, initialValue=1)
     */
    private $toolId;

    /**
     * @var string
     *
     * @ORM\Column(name="tool_identifier", type="string", length=255, nullable=true)
     */
    private $toolIdentifier;

    /**
     * @var boolean
     *
     * @ORM\Column(name="tool_default_enabled", type="boolean", nullable=false)
     */
    private $toolDefaultEnabled = false;

    /**
     * @var string
     *
     * @ORM\Column(name="tool_xml_nodeprefix", type="string", length=50, nullable=false)
     */
    private $toolXmlNodeprefix = "tool";

    /**
     * @var string
     *
     * @ORM\Column(name="tool_xml_nodevalue", type="string", length=50, nullable=true)
     */
    private $toolXmlNodevalue;


    /**
     * Get toolId
     *
     * @return integer
     */
    public function getToolId()
    {
        return $this->toolId;
    }

    /**
     * Set toolIdentifier
     *
     * @param string $toolIdentifier
     * @return LexTool
     */
    public function setToolIdentifier($toolIdentifier)
    {
        $this->toolIdentifier = $toolIdentifier;

        return $this;
    }

    /**
     * Get toolIdentifier
     *
     * @return string
     */
    public function getToolIdentifier()
    {
        return $this->toolIdentifier;
    }

    /**
     * Set toolDefaultEnabled
     *
     * @param boolean $toolDefaultEnabled
     * @return LexTool
     */
    public function setToolDefaultEnabled($toolDefaultEnabled)
    {
        $this->toolDefaultEnabled = $toolDefaultEnabled;

        return $this;
    }

    /**
     * Get toolDefaultEnabled
     *
     * @return boolean
     */
    public function getToolDefaultEnabled()
    {
        return $this->toolDefaultEnabled;
    }

    /**
     * Set toolXmlNodeprefix
     *
     * @param string $toolXmlNodeprefix
     * @return LexTool
     */
    public function setToolXmlNodeprefix($toolXmlNodeprefix)
    {
        $this->toolXmlNodeprefix = $toolXmlNodeprefix;

        return $this;
    }

    /**
     * Get toolXmlNodeprefix
     *
     * @return string
     */
    public function getToolXmlNodeprefix()
    {
        return $this->toolXmlNodeprefix;
    }

    /**
     * Set toolXmlNodevalue
     *
     * @param string $toolXmlNodevalue
     * @return LexTool
     */
    public function setToolXmlNodevalue($toolXmlNodevalue)
    {
        $this->toolXmlNodevalue = $toolXmlNodevalue;

        return $this;
    }

    /**
     * Get toolXmlNodevalue
     *
     * @return string
     */
    public function getToolXmlNodeValue()
    {
        return $this->toolXmlNodevalue;
    }

    /**
     * Evaluate if this tool is enabled for a map
     * @param Map $map
     * @return boolean
     */
    public function isEnabledFor(Map $map)
    {
        return $map->hasTool($this);
    }
}

site/src/OwsContextBundle/Controller/OwsContextController.php
<?php

namespace Carmen\OwsContextBundle\Controller;

use Carmen\ApiBundle\Controller\BaseController;
use Carmen\ApiBundle\Entity\Account;
use Carmen\ApiBundle\Entity\FavoriteArea;
use Carmen\ApiBundle\Entity\LexDns;
use Carmen\ApiBundle\Entity\Map;
use Carmen\ApiBundle\Entity\MapLocator;
use Carmen\ApiBundle\Entity\MapOnlineResources;
use Carmen\ApiBundle\Entity\UiModel;
use Carmen\ApiBundle\Exception\ApiException;
use Carmen\ApiBundle\Repository\MapTreeRepository;
use Doctrine\ORM\EntityNotFoundException;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Process\Process;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Carmen OWS Context Controller.
 *
 * @author alkante <support@alkante.com>
 *
 * @Route("/owscontext")
 */
class OwsContextController extends BaseController
{
    const ENTITY_BUNDLE = "CarmenApiBundle:";
    /**
     * Generated Formats
     * @var array
     */
    protected static $FORMATS = array("ows" => true, "json" => false, "geojson" => true);

    /**
     * Create and attributes rights on directory recursively
     * @param string $directory
     */
    protected function getOWSDirectory(&$directory)
    {
        $request = $this->getRequest();
        $directory = $request->request->get("directory", $directory ?: $this->getCarmenConfig()->getOwscontextPublicationDir());
        @mkdir($directory, 0770, true);
    }

    /**
     *
     * @param int|string $identifier
     * @return Map
     * @throws ApiException
     * @throws EntityNotFoundException
     */
    protected function getMap($identifier)
    {
        if ($identifier === null) {
            $exception = new EntityNotFoundException();
            throw new ApiException($this->_t("Not Found"), array(), Response::HTTP_NOT_FOUND, $exception);
        }
        $criteria = array();
        if (is_numeric($identifier)) {
            $criteria["mapId"] = $identifier;
        } else {
            $criteria["mapFile"] = $identifier;
            $criteria["publishedMap"] = null;
        }

        $entity = $this->getRepository(self::ENTITY_BUNDLE . "Map")->findOneBy($criteria);
        if (!$entity) {
            $exception = new EntityNotFoundException();
            throw new ApiException($this->_t("Not Found"), array(), Response::HTTP_NOT_FOUND, $exception);
        }
        $entity instanceof Map;

        return $entity;
    }

    /**
     * get local layers legend Infos since to mapserver templating in json format
     *
     * @param layers
     * @param accountUrlData datacarto server URL
     * @param mapfile mapfile path
     * @return Array
     *
     */
    protected function getLegendParams($layers, $accountUrlData, $mapfile, $legendPath, $legendUrl){
        
        $tabLegend = array();
        $tabExternalLegend = array();
        $getLegendJsonUrl = $accountUrlData.
                            $mapfile.
                            "?MODE=LEGEND";

        foreach ($layers as $layer) {
            $layer instanceof Layer;

            //test if uploaded image exists for legend, take it if exists
            $imageName = str_replace("/", "_", $mapfile)."_".$layer->getLayerMsName().".png";
            if (file_exists($legendPath.$imageName)){
                $tabExternalLegend[$layer->getLayerMsName()] = array("external_url" => $legendUrl.$imageName);
            }else{
                $layerTypeCode = $layer->getLayerType()->getLayerTypeCode();
                if($layerTypeCode==="VECTOR" || $layerTypeCode==="POSTGIS" || $layerTypeCode==="WFS"){
                    
                    $legend = strip_tags($this->curl($getLegendJsonUrl."&layer=".$layer->getLayerMsName()));
                    //suppression de la virgule
                    $legend = substr($legend, 0, -1);
                    $legend = "[".$legend."]";
                    //valid json ?
                    
                    $jsonLegend = json_decode($legend);
    
                    if (json_last_error() === JSON_ERROR_NONE) {
                        // JSON is valid
                        $tabLegend[$layer->getLayerMsName()] = $legend;
                    }
                }
            }

            
        }


        return array($tabLegend, $tabExternalLegend);
    }


    /**
     * Generate an OWS Context file for a map file given by identifier (map ID or map Filename)
     * (Generated Formats : .ows(=xml) + .json)
     *
     * @Route("/generate/{account_id}/{map_id}/{mapfile}", name="carmen_owscontext_generate", options={"expose"=true}, methods={"GET"})
     *
     * @param string $identifier
     * @param string $directory
     * @param boolean $bGetResponseObj
     * @return \Symfony\Component\HttpFoundation\Response|boolean
     * @throws ApiException
     */
    public function generateContextAction($prefix, $account_id, $map_id, $mapfile, $directory = null, $bGetResponseObj = true, $bForPublication = true)
    {
        $kernel = $this->get('kernel');
        $kernel instanceof Kernel;
        $map = $this->getMap($map_id);

        $config = $this->container->getParameter('carmen_config', array());

        //fullMapfilePath not always set
        if ($map->getFullMapfilePath() == "") {
            $map->setFullMapfilePath($config["mapserver"]["root_data"] . "/" . $map->getAccount()->getAccountPath() . "/Publication/" .
                ($map->getMapModel() ? "modele_" . preg_replace("!^modele_!", "", $mapfile) : $mapfile) . ".map");
            $map->setMapfileName(($map->getMapModel() ? "modele_" . preg_replace("!^modele_!", "", $mapfile) : $mapfile));
        }

        $mapTree = $this->getRepository(self::ENTITY_BUNDLE . 'MapTree');
        $mapTree instanceof MapTreeRepository;
        $mapTreePrint = $this->getRepository(self::ENTITY_BUNDLE . 'MapTreePrint');
        $mapTreePrint instanceof MapTreeRepository;

        $cgi_url = $config["mapserver"]["cgi_url"];

        $accountUrlFront = "/";
        $accountUrlData = "/";
        $repository = $this->getRepository('CarmenApiBundle:Account');
        $repository instanceof \Doctrine\ORM\EntityRepository;
        $account = $repository->find($account_id);
        $account instanceof Account;
        $accountDns = "";
        if ($account) {
            $accountDns = $account->getAccountDns();
            $accountDns instanceof LexDns;
            $conf = $this->container->getParameter('carmen_config');
            $sep = isset($conf['carmen']['dns_url_prefix_sep']) ? $conf['carmen']['dns_url_prefix_sep'] : '.';
            if ($accountDns) {
                $accountUrlFront = $account->getAccountUrlFront($bForPublication, $kernel->getEnvironment(), $sep);
                $accountUrlData = $account->getAccountUrlData($bForPublication, $kernel->getEnvironment(), $sep);
            } else {
                $accountDns = "";
            }
        }
        // MapLocator
        $mapLocators = array();
        $tabLocatorsGeoJson = array();
        foreach ($map->getLocators() as $locator) {
            $locator instanceof MapLocator;
            $layerLocator = $map->getLayerById($locator->getLocatorCriteriaLayerId());
            if ($layerLocator) {
                $locatorString = array(
                    $locator->getLocatorCriteriaName(),
                    $layerLocator->getLayerMsname(),
                    $locator->getLocatorCriteriaFieldId(),
                    $locator->getLocatorCriteriaFieldName(),
                    ($locator->getLocatorCriteriaVisibility() ? "1" : "0"),
                );
                $tabLocatorsGeoJson[$locator->getLocatorCriteriaRank()] = array(
                    "title" => $locator->getLocatorCriteriaName(),
                    "layerId" => $layerLocator->getLayerMsname() . "_" . $locator->getLocatorCriteriaRank(),
                    "layerCodeField" => $locator->getLocatorCriteriaFieldId(),
                    "layerWFSUrl" => $accountUrlData . "/" . $cgi_url . "/" . $map->getMapFile() . "?typename=" . $layerLocator->getLayerMsname() . "_" . $locator->getLocatorCriteriaRank() . "_locator",
                    "layerTextField" => $locator->getLocatorCriteriaFieldName(),
                    "criteriaRelated" => (($relatedLocator = $locator->getLocatorCriteriaRelated()) ? $relatedLocator->getLocatorCriteriaRank() + 1 : ""),
                    "criteriaFieldRelated" => (($relatedLocator = $locator->getLocatorCriteriaRelated()) ? $locator->getLocatorCriteriaRelatedField() : ""),
                    "criteriaInSearch" => ($locator->getlocatorInGlobalMapSearchEngine() ? true : false),
                );
                if (($relatedLocator = $locator->getLocatorCriteriaRelated())) {
                    $locatorString[] = $relatedLocator->getLocatorCriteriaRank() + 1;
                    $locatorString[] = $locator->getLocatorCriteriaRelatedField();
                }
                $mapLocators[$locator->getLocatorCriteriaRank()] = implode("|", $locatorString);
            }
        }
        ksort($mapLocators);
        ksort($tabLocatorsGeoJson);
        $mapLocators = implode(";", $mapLocators);
        $mapLocatorsGeoJson = json_encode($tabLocatorsGeoJson);

        // MapModels
        $tabModel = array();
        $tabModelGeoJson = array();
        foreach ($map->getMapUi()->getUiModels() as $uimodel) {
            $uimodel instanceof UiModel;
            $tabModel[] = $uimodel->getAccountModel()->getAccountModelFile() . "@" . $uimodel->getAccountModel()->getAccountModelName();
            $tabModelGeoJson[] = array(
                "file" => $uimodel->getAccountModel()->getAccountModelFile(),
                "title" => $uimodel->getAccountModel()->getAccountModelName(),
                "image" => $this->container->getParameter("PRODIGE_URL_FRONTCARTO") . "/IHM/cartes/" . $uimodel->getAccountModel()->getAccountModelLogo(),
                "ratio" => array("A4" => 1, "A3" => 1)
            );

site/src/WebBundle/Controller/DefaultController.php
<?php

namespace Carmen\WebBundle\Controller;

use Carmen\ApiBundle\Controller\BaseController;
use JMS\SecurityExtraBundle\Annotation\Secure;
use JMS\Serializer\SerializationContext;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

//use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * @author alkante
 */
class DefaultController extends BaseController
{
    /**
     * @isGranted("ROLE_USER")
     * @Route("/", name="carmen_ws_index", options={"expose"=true})
     */
    public function indexAction(Request $request, ContainerInterface $container)
    {
        $session = $request->getSession();

        if ($request->get('from', false) !==  'prodige') {
            $session->clear();
        }

        $uuid = $session->get('uuid', null);

        if ($uuid) {
            $serializer = $container->get('jms_serializer');
            $context = new SerializationContext();
            $context->setSerializeNull(true);
            $user = $serializer->serialize($this->getUser(), 'json', $context);

            $config = $container->get('carmen_config')->getWebConfig();
            $defaults = $container->getParameter('jsdefaults', array());
            $defaults["PROJECTION"] = (defined("PRO_IMPORT_EPSG") ? PRO_IMPORT_EPSG : $this->container->getParameter('PRODIGE_DEFAULT_EPSG'));

            $connection = $this->getDoctrine()->getConnection();
            if ($connection) {
                try {
                    $settings = $connection->fetchAll("select prodige_settings_constant, prodige_settings_value from parametrage.prodige_settings");
                    foreach ($settings as $row) {
                        $config[$row["prodige_settings_constant"]] = $row["prodige_settings_value"];
                    }
                } catch (\Exception $exception) {
                }
            }
            // return $this->render('CarmenWebBundle:Default:index.html.twig', array(
            return $this->render('WebBundle/Default/index.html.twig', array(
                'user' => $user,
                'parameters' => $config,
                'jsdefaults' => $defaults,
                'isAdmin' => $request->get('isAdmin', 0)
            ));
        } else {
            // on est normalement ejecté avant par les vérif niveau CasProvider
            return $this->createAccessDeniedException("Paramètre manquant : uuid");
        }
    }
    
    /**
     * Returns the default DBAL PDO Connection.
     * 
     * @return \Doctrine\DBAL\Driver\PDOConnection
     */
    protected function getConnection($connection_name = null, $schema = "carmen")
    {
        return $this->getDoctrine()->getConnection();
    }
}

site/templates/OwsContextBundle/Default/context.json.twig
{% import 'OwsContextBundle/Default/context.macros.twig' as macros %}

{
  "OWSContext": {
    "attributes": {
      "version": "1.1.0",
      "id": "{{ map.mapFile|e('url') }}",
      "schemaLocation": "http:\/\/www.opengeospatial.net\/context context.xsd"
    },
    "General": {
      "BoundingBox": {
        "LowerCorner": "{{ map.mapExtentXmin }} {{ map.mapExtentYmin }}",
        "UpperCorner": "{{ map.mapExtentXmax }} {{ map.mapExtentYmax }}",
        "attributes": {
          "crs": "+init={% if map.mapProjectionEpsg is not null %}{{ map.mapProjectionEpsg.projectionProvider }}:{{ map.mapProjectionEpsg.projectionEpsg }}{% else %}epsg:2154{% endif %}"
        }
      },
      "MaxBoundingBox": {
        "LowerCorner": "{{ map.mapExtentXmin }} {{ map.mapExtentYmin }}",
        "UpperCorner": "{{ map.mapExtentXmax }} {{ map.mapExtentYmax }}",
        "attributes": {
          "crs": "+init={% if map.mapProjectionEpsg is not null %}{{ map.mapProjectionEpsg.projectionProvider }}:{{ map.mapProjectionEpsg.projectionEpsg }}{% else %}epsg:2154{% endif %}"
        }
      },
      "Title": "{{ map.mapTitle|e('url') }}",
      "KeywordList": [
      {% for keyword in map.keywords %}
      { "Keyword" : "{{ (keyword.category.categoryName ~ ' - ' ~ keyword.keywordName)|e('url') }}" }{% if not loop.last %},{% endif %}
      {% endfor %}
      ],
  {% if mapUI.uiLogo %}
      "LogoURL": {
        "attributes": {
          "width": "44",
          "height": "25",
          "format": "gif"
        },
        "OnlineResource": {
          "attributes": {
            "href": "{{ mapUI.uiLogopath }}"
          }
        }
      },
  {% endif %}
      "Extension": {
        "display_header": "{{ mapUI.uiBanner|ON_OFF }}",
        "header_model": "{{ mapUI.uiBannerFile|e('url') }}",
        "inspire_flag": "1",
        
        "MINSCALEDENOM": "{{ map.mapMinscale }}",
        "MAXSCALEDENOM": "{{ map.mapMaxscale }}",
        "RESUME": "{{ map.mapSummary|e('url') }}",
        
        "AJOUT_COUCHE": "ON",
        "AJOUT_COUCHE_WFS": "ON",
        "EXT_THEME_COLOR": "{% if mapUI.uiColor is not null %}{{ mapUI.uiColor.colorKey }}{% else %}olive{% endif %}",
        "OUTIL_TRANSPARENCE": "ON",
        "COMMENTAIRE": null,
        "mapSettings_inlay" :"1",
        "mapSettings_pwd": "{{ map.mapPassword|e('url') }}",
        "mapSettings_copyright": "{{ mapUI.uiCopyright|ZERO_ONE }}",
        "mapSettings_copyrightTxt": "{{ mapUI.uiCopyrightText|e('url') }}",
        "mapSettings_logo": "{{ mapUI.uiLogo|ZERO_ONE }}",
        "mapSettings_logoPath": "{{ (accountUrlFront ~ '/IHM/IHM/' ~ account.accountPath ~ '/' ~ mapUI.uiLogopath) }}",
        "mapSettings_backgroundImageColor": "{{ map.mapBgcolor|e('url') }}",
        
        "mapSettings_inCatalogue": "{{ map.mapCatalogable|ON_OFF }}",
        
        "mapSettings_layoutModels":  "{{ mapModels|e('url') }}",
        
  {% for tool in tools %}
        "{{ tool.toolXmlNodeprefix }}_{{ tool.toolIdentifier }}" : "{% if tool.toolXmlNodeprefix == "mapSettings" %}{{ tool.isEnabledFor(map)|ZERO_ONE }}{% else %}{{ tool.isEnabledFor(map)|ON_OFF }}{% endif %}",
    {% set maptool = map.getMaptool(tool) %}
    {% if maptool is not null and tool.toolXmlNodeValue is not null %}
        "{{ tool.toolXmlNodeprefix }}_{{ tool.toolXmlNodeValue }}" : "{{ maptool.getMaptoolValue() }}",
    {% endif %}
  {% endfor %}
  
  
        "tool_focus" : "{{ mapUI.uiFocus|ON_OFF }}",
        "tool_referenceMap" : "{{ mapUI.uiKeymap|ON_OFF }}",
        "tool_legend" : "{{ mapUI.uiLegend|ON_OFF }}",
        "tool_legendPrint" : "{{ mapUI.uiLegendPrint|ON_OFF }}",
         
        "tool_zoomToPlace" : "{{ mapUI.uiLocate|ON_OFF }}",
        "tool_zoomToPlaceConfig" : "{{ mapLocators|e('url') }}",
        "zones_favorites" : "{{ favoriteAreas|e('url') }}",
        
        "ReferenceMap": {
          "attributes": {
            "width": "180",
            "height": "100"
          },
          "BoundingBox": {
            "attributes": {
              "crs": "+init={% if map.mapProjectionEpsg is not null %}{{ map.mapProjectionEpsg.projectionProvider }}:{{ map.mapProjectionEpsg.projectionEpsg }}{% else %}epsg:2154{% endif %}"
            },
		 	{% if map.mapRefmapExtentXmin is not null %}
            "LowerCorner": "{{map.mapRefmapExtentXmin}} {{map.mapRefmapExtentYmin}}",
            "UpperCorner": "{{map.mapRefmapExtentXmax}} {{map.mapRefmapExtentYmax}}"
            {% else %}
            "LowerCorner": "{{ map.mapExtentXmin }} {{ map.mapExtentYmin }}",
            "UpperCorner": "{{ map.mapExtentXmax }} {{ map.mapExtentYmax }}"
            {% endif %}
          },
          "OnlineResource": {
            "attributes": {
              "href": "{{ (accountUrlFront ~ '/IHM/IHM/' ~ account.accountPath ~ '/' ~ map.mapRefmapImage) }}"
            }
          }
        },
        "LayerTree"     : {{ macros.getLayerTree(map_tree, 'json', 0, _context) }},
        "LayerTreePrint": {{ macros.getLayerTree(map_tree_print, 'json', 0, _context) }},
        "Labels" :  {
		      "Layer": [
		{% for layer in layers %}
          {% if layer.layerHasLabel is defined %}
		    {% if not loop.first %},{% endif %}
		      {{ macros.writeLayer(layer, 'json', _context) }}
                {% endif %}
		    {% endfor %}

		      ] 
		    }
      } 
    },
    "ResourceList": {
      "Layer": [
    {% for layer in layers %}
      {{ macros.writeLayer(layer, 'json', _context) }}
      {% if not loop.last %},{% endif %}
    {% endfor %}
      ] 
    }
  }
}